<a href="https://colab.research.google.com/github/Santiago193/1015-scastillo-numpy-data-engineering-practice/blob/main/tallernumpyPractica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#taller de numPy
Autor:Santiago Castillo


fecha: 16/04/2026

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/TU_USUARIO/TU_REPOSITORIO/blob/main/TU_ARCHIVO.ipynb)

#Unidad 1

##Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.

In [ ]:
lista = [x for x in range(1, 101) if x % 7 == 0]
print(lista)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


##Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}

In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

a) Crea una lista con las claves cuyo valor sea mayor a 12.


In [ ]:
lista1 = [clave for clave, valor in datos.items() if valor > 12]
print(lista1)

['b', 'd']


b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado.


In [ ]:

diccionario2 = {clave: valor*valor for clave,valor in datos.items()}
print (diccionario2)


{'a': 100, 'b': 625, 'c': 49, 'd': 324}


##Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con: longitud, suma, promedio, mínimo y máximo de la lista.


In [ ]:
def resumen(lista):
    dicc = {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista)/len(lista),
        'minimo': min(lista),
        'maximo': max(lista),
    }
    return dicc

resultadoej3 = [l for l in range(1, 10)]
resultado = resumen(resultadoej3)
print(resultado)

{'longitud': 9, 'suma': 45, 'promedio': 5.0, 'minimo': 1, 'maximo': 9}


##Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:
lista = [1,2,3,4,5]
mapa = list(map(lambda x: x**3, lista))
print(mapa)

[1, 8, 27, 64, 125]


#Unidad 2

##Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):

a) Vector con enteros del 1 al 20.


In [ ]:
import numpy as np
v = np.array([x for x in range (1,21)])
print(v)
print(v.shape)
print(v.dtype)
print(v.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
int64
1


b) Matriz de ceros de 5 filas y 3 columnas.


In [ ]:
import numpy as np
ceros = np.zeros((5,3))
print(ceros)
print(ceros.shape)
print(ceros.dtype)
print(ceros.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)
float64
2


c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
import numpy as np
puntos = np.linspace(-1,1,10)
print(puntos)
print(puntos.shape)
print(puntos.dtype)
print(puntos.ndim)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
(10,)
float64
1


##Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
##Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].

In [ ]:
import numpy as np
np.random.seed(99)
matriz = np.random.randint(0,50,(4,4))
print(matriz)
print(matriz.shape)
print(matriz.dtype)
print(matriz.nbytes)
print(matriz[2,3])

[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
(4, 4)
int64
128
49


##Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código

In [ ]:
np.array([1,2,3])
np.array([1.0,2.0,3.0])
print (np.array([1,2,3]).dtype)
print (np.array([1.0,2.0,3.0]).dtype)
#la diferencia es que el primero genera un arreglo de números enteros
#y el segundo con datos de tipo flotante

int64
float64


##Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace()).

In [ ]:
identidad = np.identity(5)
print(identidad)
print(np.trace(identidad))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5.0


#Unidad 3

##Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)


a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.


In [ ]:
A = np.arange(1, 26).reshape(5, 5)
print(A)
print(A[2:,:3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12 13]
 [16 17 18]
 [21 22 23]]


b) Extrae la segunda columna completa.


In [ ]:
print(A[0:,1])

[ 2  7 12 17 22]


c) Extrae los elementos de los ángulos (esquinas) de la matriz.

In [ ]:
print(A)
print(A[0,0],A[0,4],A[4,0],A[4,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1 5 21 25


##Ejercicio 2: Con la misma matriz A:


a) Crea una máscara booleana para los valores mayores a 12.

In [ ]:
mascara = A >12
print(mascara)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


b) Reemplaza esos valores por -1 en una copia del array.


In [ ]:
copia = A.copy()
copia[A>12]= -1
print (copia)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


c) Usa np.where para reemplazar impares por 0 y mantener los pares.

In [ ]:
A=np.where(A%2!=0,0,A)
print(A)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


##Ejercicio 3: Crea un vector de 24 elementos con arange(24).
##Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24.

In [ ]:
nuevo = np.arange(24)
print(nuevo)
print("")
print(nuevo.reshape(6,4))
print("")
print(nuevo.reshape(2,3,4))
print("")
print(nuevo.reshape(1,24))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


##Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento en un slice y verifica que el array original también cambia.

In [ ]:
import numpy as np
original = np.array([10, 20, 30, 40, 50])
print(f"Original antes: {original}")
vista_slice = original[0:3]
vista_slice[0] = 999
print(f"Vista modificada: {vista_slice}")
print(f"Original después: {original}")

Original antes: [10 20 30 40 50]
Vista modificada: [999  20  30]
Original después: [999  20  30  40  50]


#Unidad 4

##Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).


In [ ]:
import numpy as np
np.random.seed(7)
matriz = np.random.randint(1, 101, size=(5, 4))
print("Matriz Original:")
print(matriz)
print("-" * 30)

Matriz Original:
[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]
------------------------------


a) Calcula la media, máximo y mínimo de cada columna.


In [ ]:
media_col = matriz.mean(axis=0)
max_col = matriz.max(axis=0)
min_col = matriz.min(axis=0)

print("a) Estadísticas por columna:")
print(f"Medias: {media_col}")
print(f"Máximos: {max_col}")
print(f"Mínimos: {min_col}")
print("-" * 30)

a) Estadísticas por columna:
Medias: [51.8 51.4 41.8 60.2]
Máximos: [84 91 93 90]
Mínimos: [15 24  8 40]
------------------------------


b) Calcula la suma acumulada de la primera fila.


In [ ]:
suma_acum_fila1 = np.cumsum(matriz[0, :])

print(f"b) Suma acumulada de la primera fila: {suma_acum_fila1}")
print("-" * 30)

b) Suma acumulada de la primera fila: [ 48 117 143 211]
------------------------------


c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
Fórmula: (x - min_col) / (max_col - min_col)



In [ ]:
matriz_normalizada = (matriz - min_col) / (max_col - min_col)

print("c) Matriz normalizada (valores entre 0 y 1):")
print(matriz_normalizada)

c) Matriz normalizada (valores entre 0 y 1):
[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


##Ejercicio 2: Usando broadcasting:

a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].


In [ ]:
import numpy as np

fila = np.array([1, 2, 3, 4])

columna = np.array([[10], [20], [30]])

print(f"Fila shape: {fila.shape}")
print(f"Columna shape: {columna.shape}")

Fila shape: (4,)
Columna shape: (3, 1)


b) Suma ambos vectores y explica el shape del resultado.


In [ ]:
resultado = fila + columna

print("\nResultado de la suma:")
print(resultado)
print(f"\nShape del resultado: {resultado.shape}")


Resultado de la suma:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

Shape del resultado: (3, 4)


##Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:

In [ ]:
import numpy as np

nombres = np.array(["Ana", "Betto", "Carla", "Daniel", "Elena"])
notas = np.array([85, 42, 90, 55, 78])

promedio = notas.mean()
print(f"Promedio de la clase: {promedio:.2f}")
print("-" * 30)

Promedio de la clase: 70.00
------------------------------


a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)


In [ ]:
mascara = notas > promedio
cantidad = np.sum(mascara)  # True cuenta como 1, False como 0

print(f"a) Cantidad de estudiantes sobre el promedio: {cantidad}")

a) Cantidad de estudiantes sobre el promedio: 3


b) Imprime solo los nombres de esos estudiantes.

In [ ]:
nombres_top = nombres[mascara]

print(f"b) Estudiantes destacados: {nombres_top}")

b) Estudiantes destacados: ['Ana' 'Carla' 'Elena']


##Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
##Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [ ]:
import numpy as np

A = np.zeros((3, 4)) + 1
B = np.zeros((3, 4)) + 2

vertical = np.vstack((A, B))

horizontal = np.hstack((A, B))

print("Concatenación Vertical (Shape: 6x4):")
print(vertical)
print("\nConcatenación Horizontal (Shape: 3x8):")
print(horizontal)
print("-" * 30)

partes = np.vsplit(vertical, 3)

print("Resultado de vsplit (3 partes de 2x4 cada una):")
for i, p in enumerate(partes):
    print(f"Parte {i+1}:\n{p}")

Concatenación Vertical (Shape: 6x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]

Concatenación Horizontal (Shape: 3x8):
[[1. 1. 1. 1. 2. 2. 2. 2.]
 [1. 1. 1. 1. 2. 2. 2. 2.]
 [1. 1. 1. 1. 2. 2. 2. 2.]]
------------------------------
Resultado de vsplit (3 partes de 2x4 cada una):
Parte 1:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Parte 2:
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
Parte 3:
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
